config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  get 'chat_comments/create'
  get 'schools/new'
  get 'favorites/create'
  root 'pages#index'
  get 'sessions/new'
  post '/login',to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'
  put '/edit/haiku',to:'haikus#update'
  get '/haikus/:id/edit',to:'haikus#edit',as: 'edit_haikus'
  get 'haikus/search'
  post '/favorites',to: "favorites#create"
  get 'users/favorite_haiku'
  get 'haikus/favorite_haiku'
  get 'users/sort/:id',to:'users#sort',as: 'sort_users'
  get '/sort',to:'pages#sort',as:'sort_pages'
  get 'schools/search'
  get 'pages/pagenate',to:'pages#pagenate'
  get 'users/pagenate',to:'users#pagenate'
  

  # get "users/:id", to: "users#show", as: "user_path"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages
  resources :users
  resources :haikus
  resources :comments
  resources :favorites
  resources :schools
  resources :chats
  resources :chat_comments
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :haiku
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @favorite = Favorite.new
    @favorite.haiku_id = params[:haiku_id]
    @favorite.user_id = carrent_user.id
    @haiku = Haiku.find_by(id: params[:haiku_id])
    if @favorite.save
      flash.now[:info] = 'いいねしました'
      # render template: 'pages/index'
      # redirect_to pages_path
    else
      flash[:danger] = 'いいねできませんでした'
      redirect_to pages_path
    end
    # binding.pry
  end

  def destroy
    @favorite = Favorite.find_by(haiku_id: params[:haiku_id],user_id: carrent_user.id)
    @haiku = Haiku.find_by(id: params[:haiku_id])
    if @favorite.delete
      flash[:info] = 'いいねを削除しました'
      # redirect_to pages_path
    else
      flash[:danger] = 'いいねを削除できませんでした'
      # redirect_to pages_path
    end
    # binding.pry
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
            <% if Favorite.find_by(haiku_id: haiku.id,user_id: carrent_user.id) %>
            <% favorite = Favorite.find_by(haiku_id: haiku.id,user_id: carrent_user.id) %>
              <%= link_to(favorite_path(favorite.id,haiku_id: haiku.id),method: :delete ,class:"haiku__favorite haiku_favorite#{haiku.id}",remote: true) do %>
              <i class="fas fa-trash-alt"></i>
              <span><%= haiku.favorites.length %>いいね済み</span>
              <% end %>
            <% else %>
            <%= link_to favorites_path(haiku_id: haiku.id),method: :post ,class:"haiku__favorite haiku_favorite#{haiku.id}",remote: true do %>
                <i class="fas fa-trash-alt"></i>
                <span><%= haiku.favorites.length %>いいね</span>
            <% end %>
            <% end %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/create.js.erb
var favorite = $(".haiku_favorite<%= params[:haiku_id] %>");
console.log("<%= params[:haiku_id] %>");
<% flash.now[:info] = 'いいねしました' %>
favorite.replaceWith("<%=j(render partial: "favorites/favorite",locals:{haiku:@haiku,} ) %>");
<%# $("body").prepend("<div class='alert alert-info position-absolute top-0 w-100'><p>いいねしました</p></div>"); %>
<%# <div class="alert alert-info position-absolute top-0 w-100"><p>いいねしました</p></div> %>


app/views/favorites/destroy.js.erb
var favorite = $(".haiku_favorite<%= params[:haiku_id] %>");
console.log("<%= params[:haiku_id] %>");
favorite.replaceWith("<%=j(render partial: "favorites/favorite",locals:{haiku:@haiku,} ) %>");