config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  get 'chat_comments/create'
  get 'schools/new'
  get 'favorites/create'
  root 'pages#index'
  get 'sessions/new'
  post '/login',to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'
  put '/edit/haiku',to:'haikus#update'
  get '/haikus/:id/edit',to:'haikus#edit',as: 'edit_haikus'
  get 'haikus/search'
  post '/favorites',to: "favorites#create"
  get 'users/favorite_haiku'
  get 'haikus/favorite_haiku'
  get 'users/sort/:id',to:'users#sort',as: 'sort_users'
  get '/sort',to:'pages#sort',as:'sort_pages'
  get 'schools/search'
  get 'pages/pagenate',to:'pages#pagenate'
  get 'users/pagenate',to:'users#pagenate'
  

  # get "users/:id", to: "users#show", as: "user_path"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages
  resources :users
  resources :haikus
  resources :comments
  resources :favorites
  resources :schools
  resources :chats
  resources :chat_comments
end

app/models/chat.rb
class Chat < ApplicationRecord
    has_many :chat_comments
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @chat = ChatComment.new
    # @chats = ChatComment.all
    @chats = Chat.find(params[:id]).chat_comments
    @chat_p = Chat.find(params[:id])
    # ActionCable.server.broadcast("chat_channel",data:'aaa')
  end

  def index
    @chats = Chat.all.order("id DESC").page(params[:page]).per(4)
  end

  def new
    @chat = Chat.new
  end

  def create
    @chat = Chat.new(chat_params)

    if @chat.save
      flash[:info] = '投稿しました'
      redirect_to chats_path
    else
      flash[:danger] = '投稿に失敗しました'
      render :new
    end
  end
end

private
def chat_params
  params.require(:chat).permit(:chat1,:chat2,:chat3,:user_id)
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/index.html.erb
<div class="row my-3">
    <%= link_to 'チャットルームを作成', new_chat_path,class:'btn btn-block btn-primary col-sm-6 offset-sm-2 px-3' %>
</div>
<div class=" row" >
  <div class=" col-sm-6 offset-sm-2">
    <% @chats.each do |chat| %>
      <div class=" row" >
      <div class=" col-sm-12 my-3">
        <div class="card border border-success rounded">
          <div class="card-body">
            <p class="haiku__text"><span><%= chat.chat1 %></span></p>
            <p class="haiku__text"><span><%= chat.chat2 %></span></p>
            <p class="haiku__text"><span><%= chat.chat3 %></span></p>
          </div>
          <div class="card-footer border-success">
            <%= link_to 'コメント', chat_path(chat.id) %>
          </div>
        </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-sm-4 banner my-3">
      <%= image_tag 'banner_pc.png',class:'pc'%>
      <%= image_tag 'banner_sp.png',class:'sp'%>
  </div>
</div>
<div class="row" id="haikus_paginate">
  <div class="col-sm-6 offset-sm-2 mx-auto">
    <%= paginate @chats %>
  </div>
  <div class="col-sm-6 offset-sm-2 mx-auto vw-375 sm-btn">
    <%= link_to_next_page @chats,'次へ',class:'btn btn-secondary btn-block',remote:true%>
  </div>
</div>



app/views/chats/new.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2">
  <h1>新規ルーム作成</h1>
  <%= form_with model:@chat,local:true do |form| %>
    <div class="form-group">
      <%= form.label :chat1 %>
      <%= form.text_field :chat1,class:('form-control') %>
      <% if  @chat.errors.any? %>
          <p><%= @chat.errors.full_messages_for(:chat1).first %></p>
      <% end %>
    </div>
    <div class="form-group">
      <%= form.label :chat2 %>
      <%= form.text_field :chat2,class:('form-control') %>
      <% if  @chat.errors.any? %>
          <p><%= @chat.errors.full_messages_for(:chat2).first %></p>
      <% end %>
    </div>
    <div class="form-group">
      <%= form.label :chat3 %>
      <%= form.text_field :chat3,class:('form-control') %>
      <% if  @chat.errors.any? %>
          <p><%= @chat.errors.full_messages_for(:chat3).first %></p>
      <% end %>
    </div>
    <%= form.hidden_field :user_id,value:session[:user_id] %>
    <%= form.submit :送信,class:('btn btn-secondary btn-block')%>
  <% end %>
  </div>
</div>

app/views/chats/show.html.erb
<div class=" row my-3" >
  <div class=" col-sm-6 offset-sm-3">
  <h1>チャットルーム</h1>
    <div class="card border border-success rounded">
      <div class="card-body">
        <p class="haiku__text"><span><%= @chat_p.chat1 %></span></p>
        <p class="haiku__text"><span><%= @chat_p.chat2 %></span></p>
        <p class="haiku__text"><span><%= @chat_p.chat3 %></span></p>
      </div>
      <div class="card-footer border-success">
        
      </div>
    </div>
  </div>

</div>
<div class="row">
  <div class="col-sm-4 banner my-3  offset-sm-4">
      <%= image_tag 'banner_pc.png',class:'pc'%>
      <%= image_tag 'banner_sp.png',class:'sp'%>
  </div>
</div>
<div id="chats">
  <% @chats.each do |chat| %>
  <div class=" row my-3" >
    <div class=" col-sm-4 offset-sm-4">
      <div class="card border border-success rounded">
        <div class="card-body">
          <p class="haiku__text"><span><%= chat.chat1 %></span></p>
          <p class="haiku__text"><span><%= chat.chat2 %></span></p>
          <p class="haiku__text"><span><%= chat.chat3 %></span></p>
        </div>
        <div class="card-footer border-success">
          <%= chat.user.name %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

<div class="row">
  <div class="col-sm-4 offset-sm-4">
  
  <%= form_with model:@chat,remote:true do |form| %>
    <div class="form-group">
      <%= form.label :chat1 %>
      <%= form.text_field :chat1,class:('form-control') %>
      <% if  @chat.errors.any? %>
          <p><%= @chat.errors.full_messages_for(:chat1).first %></p>
      <% end %>
    </div>
    <div class="form-group">
      <%= form.label :chat2 %>
      <%= form.text_field :chat2,class:('form-control') %>
      <% if  @chat.errors.any? %>
          <p><%= @chat.errors.full_messages_for(:chat2).first %></p>
      <% end %>
    </div>
    <div class="form-group">
      <%= form.label :chat3 %>
      <%= form.text_field :chat3,class:('form-control') %>
      <% if  @chat.errors.any? %>
          <p><%= @chat.errors.full_messages_for(:chat3).first %></p>
      <% end %>
    </div>
    <%= form.hidden_field :user_id,value:session[:user_id] %>
    <%= form.hidden_field :chat_id,value:params[:id] %>
    <%= form.submit :送信,class:('btn btn-secondary btn-block'),id:'btn_chat'%>
  <% end %>
  </div>
</div>