config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  get 'chat_comments/create'
  get 'schools/new'
  get 'favorites/create'
  root 'pages#index'
  get 'sessions/new'
  post '/login',to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'
  put '/edit/haiku',to:'haikus#update'
  get '/haikus/:id/edit',to:'haikus#edit',as: 'edit_haikus'
  get 'haikus/search'
  post '/favorites',to: "favorites#create"
  get 'users/favorite_haiku'
  get 'haikus/favorite_haiku'
  get 'users/sort/:id',to:'users#sort',as: 'sort_users'
  get '/sort',to:'pages#sort',as:'sort_pages'
  get 'schools/search'
  get 'pages/pagenate',to:'pages#pagenate'
  get 'users/pagenate',to:'users#pagenate'
  

  # get "users/:id", to: "users#show", as: "user_path"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages
  resources :users
  resources :haikus
  resources :comments
  resources :favorites
  resources :schools
  resources :chats
  resources :chat_comments
end

app/models/school.rb
class School < ApplicationRecord
    validates :haiku1,presence:true,length:{in: 4..7}
    validates :haiku2,presence:true,length:{in: 5..9}
    validates :haiku3,presence:true,length:{in: 4..7}

    validates :name,presence:true
    validates :email,presence:true
    validates :address,presence:true
    
    validates :permit,inclusion:{in:[true,false]}
    # validates :user_id,presence:true
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all.order("id DESC").page(params[:page]).per(2)
  end

  def new
    @schools = School.new
  end

  def create
    @schools = School.new(school_params)
    
    if @schools.save
      flash[:info] = '受け付けました'
      redirect_to root_path
    else
      binding.pry
      render :new
      
    end
  end

  def drete
  end

  def edit
    @school = School.find(params[:id])
    binding.pry
  end

  def update
    @school = School.find(params[:id])
    @school.update(permit: params[:permit])
  end

  def search
    @schools = School.where("name LIKE ?","%#{params[:school]}%").or(School.where("address LIKE ?","%#{params[:school]}%")).or(School.where("email LIKE ?","%#{params[:school]}%")).or(School.where("haiku1 LIKE ?","%#{params[:school]}%")).or(School.where("haiku2 LIKE ?","%#{params[:school]}%")).or(School.where("haiku3 LIKE ?","%#{params[:school]}%")).page(params[:page]).per(4)
    binding.pry
  end

  private
  def school_params
    params.require(:school).permit(:name,:email,:address,:permit,:haiku1,:haiku2,:haiku3,:user_id)
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_schools.html.erb
<div id="haikus_block">
<div class="row">
    <div class="col-sm-6 offset-sm-2">
    <% schools.each do |school| %>
        <% if school.permit || carrent_user != nil && carrent_user.id == 4%>
        <div class="row">
            <div class="col-sm-12 my-3">

            <div class="card">
                <div class="card-header">
                    <p class="card-title"><%= school.name %></p>
                </div>
                <div class="card-body">
                    <p class="card-text"><%= school.haiku1 %></p>
                    <p class="card-text"><%= school.haiku2 %></p>
                    <p class="card-text"><%= school.haiku3 %></p>
                </div>
                <div class="card-footer">
                    <p class="card-text"><%= school.address %></p>
                    <p class="card-text"><%= school.email %></p>
                    <%if !school.permit && carrent_user != nil && carrent_user.id == 4 %>
                        <%= link_to '公開',school_path(school.id,permit:true),method: :patch%>
                    <% elsif school.permit && carrent_user != nil && carrent_user.id == 4 %>
                        <%= link_to '公開停止',school_path(school.id,permit:false),method: :patch%>
                        <%= link_to '更新',edit_school_path(school.id,permit:true),method: :get %>
                    <% end %>
                </div>
            </div>

            </div>
        </div>
        <% end %>
    <% end %>
    </div>
    <div class="col-sm-4 banner my-3">
        <%= image_tag 'banner_pc.png',class:'pc'%>
        <%= image_tag 'banner_sp.png',class:'sp'%>
    </div>
</div>
    <div class="row" id="haikus_paginate">
    <div class="col-sm-8 offset-sm-2">
        <%= paginate schools %>
    </div>
    <div class="col-sm-6 offset-sm-3 mx-auto vw-375 sm-btn">
        <%= link_to_next_page schools,'次へ',class:'btn btn-secondary btn-block',remote:true%>
    </div>
    </div>
</div>

app/views/schools/edit.html.erb
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1>教室情報を編集</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-8 offset-sm-2">
            <%= form_with model: @school,local:true do |form| %>
            <div class="form-group">
                <%= form.label :name %>
                <%= form.text_field :name,class:'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :address %>
                <%= form.text_field :address,class:'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :email %>
                <%= form.text_field :email,class:'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :haiku1 %>
                <%= form.text_field :haiku1,class:'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :haiku2 %>
                <%= form.text_field :haiku2,class:'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :haiku3 %>
                <%= form.text_field :haiku3,class:'form-control' %>
            </div>

            <div class="form-group">
                <%= form.hidden_field :permit %>
                <%= form.submit :送信,class:'btn btn-secondary btn-block' %>
            </div>
            <% end %>
    </div>
</div>




app/views/schools/index.html.erb
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1>教室一覧</h1>
    </div>
</div>
<% @schools.each do |school| %>
    <% if school.permit || carrent_user != nil && carrent_user.id == 4%>
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <p><%= school.name %></p>
            <p><%= school.address %></p>
            <p><%= school.email %></p>
            <%if !school.permit && carrent_user != nil && carrent_user.id == 4 %>
                <%= link_to '公開',school_path(school.id,permit:true),method: :patch%>
            <% elsif school.permit && carrent_user != nil && carrent_user.id == 4 %>
                <%= link_to '公開停止',school_path(school.id,permit:false),method: :patch%>
            <% end %>
        </div>
    </div>
    <% end %>
<% end %>

app/views/schools/index.js.erb
$("#haikus_block").append("<%= j(render partial: 'schools/schools',locals: {schools:@schools})%>");
$('#haikus_paginate').remove();
$("#haikus_paginate").html("<div class='col-sm-6 offset-sm-3 mx-auto vw-375 sm-btn' style='display:block'><%= j(link_to_next_page @schools,'次へ',class:'btn btn-secondary btn-block',remote:true)%></div>");
console.log('aaaaa');

app/views/schools/new.html.erb
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1>新規教室を追加</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-8 offset-sm-2">
            <%= form_with model: @schools,local:true do |form| %>
            <div class="form-group">
                <%= form.label :name %>
                <%= form.text_field :name,class:'form-control' %>
                <% if  @schools.errors.any? %>
                    <p><%= @schools.errors.full_messages_for(:name).first %></p>
                <% end %>
            </div>

            <div class="form-group">
                <%= form.label :address %>
                <%= form.text_field :address,class:'form-control' %>
                <% if  @schools.errors.any? %>
                    <p><%= @schools.errors.full_messages_for(:address).first %></p>
                <% end %>
            </div>

            <div class="form-group">
                <%= form.label :email %>
                <%= form.text_field :email,class:'form-control' %>
                <% if  @schools.errors.any? %>
                    <p><%= @schools.errors.full_messages_for(:email).first %></p>
                <% end %>
            </div>

            <div class="form-group">
                <%= form.label :haiku1 %>
                <%= form.text_field :haiku1,class:'form-control' %>
                <% if  @schools.errors.any? %>
                    <p><%= @schools.errors.full_messages_for(:haiku1).first %></p>
                <% end %>
            </div>

            <div class="form-group">
                <%= form.label :haiku2 %>
                <%= form.text_field :haiku2,class:'form-control' %>
                <% if  @schools.errors.any? %>
                    <p><%= @schools.errors.full_messages_for(:haiku2).first %></p>
                <% end %>
            </div>

            <div class="form-group">
                <%= form.label :haiku3 %>
                <%= form.text_field :haiku3,class:'form-control' %>
                <% if  @schools.errors.any? %>
                    <p><%= @schools.errors.full_messages_for(:haiku3).first %></p>
                <% end %>
            </div>

            <div class="form-group">
                <%= form.hidden_field :permit,value: false %>
                <%= form.submit :送信,class:'btn btn-secondary btn-block' %>
            </div>
            <% end %>
    </div>
</div>

app/views/schools/search.html.erb
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1>教室検索結果</h1>
        <%= link_to '新規教室を申請',new_school_path,class:'btn btn-primary' %>
    </div>
</div>
<%= render partial: "schools/schools",locals:{schools:@schools} %>