config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  get 'chat_comments/create'
  get 'schools/new'
  get 'favorites/create'
  root 'pages#index'
  get 'sessions/new'
  post '/login',to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'
  put '/edit/haiku',to:'haikus#update'
  get '/haikus/:id/edit',to:'haikus#edit',as: 'edit_haikus'
  get 'haikus/search'
  post '/favorites',to: "favorites#create"
  get 'users/favorite_haiku'
  get 'haikus/favorite_haiku'
  get 'users/sort/:id',to:'users#sort',as: 'sort_users'
  get '/sort',to:'pages#sort',as:'sort_pages'
  get 'schools/search'
  get 'pages/pagenate',to:'pages#pagenate'
  get 'users/pagenate',to:'users#pagenate'
  

  # get "users/:id", to: "users#show", as: "user_path"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages
  resources :users
  resources :haikus
  resources :comments
  resources :favorites
  resources :schools
  resources :chats
  resources :chat_comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    has_many :chat_comments
end

app/models/chat_comment.rb
class ChatComment < ApplicationRecord
    belongs_to :chat
    belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :haiku
    belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :haiku
end

app/models/haiku.rb
class Haiku < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :favorites
  has_many :users,through: :favorites
  validates :haiku1,presence: true,length:{in: 4..7}
  validates :haiku2,presence: true,length:{in: 5..9}
  validates :haiku3,presence: true,length:{in: 4..7}
end

app/models/school.rb
class School < ApplicationRecord
    validates :haiku1,presence:true,length:{in: 4..7}
    validates :haiku2,presence:true,length:{in: 5..9}
    validates :haiku3,presence:true,length:{in: 4..7}

    validates :name,presence:true
    validates :email,presence:true
    validates :address,presence:true
    
    validates :permit,inclusion:{in:[true,false]}
    # validates :user_id,presence:true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :haikus, dependent: :destroy
  has_many :favorites
  has_many :chat
  has_many :chat_comment
  has_many :favorite_haikus, through: :favorites,source: :haiku
  # has_many :haikus, dependent: :destroy

  validates :name , presence:true,
  length: {maximum: 20}
  validates :email , presence:true,
  uniqueness: true,
  format: {with:/.+@.+\..+/,message:"エラーが起きました"}
  validates :password_digest , presence:true,
  uniqueness:true
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @chat = ChatComment.new
    # @chats = ChatComment.all
    @chats = Chat.find(params[:id]).chat_comments
    @chat_p = Chat.find(params[:id])
    # ActionCable.server.broadcast("chat_channel",data:'aaa')
  end

  def index
    @chats = Chat.all.order("id DESC").page(params[:page]).per(4)
  end

  def new
    @chat = Chat.new
  end

  def create
    @chat = Chat.new(chat_params)

    if @chat.save
      flash[:info] = '投稿しました'
      redirect_to chats_path
    else
      flash[:danger] = '投稿に失敗しました'
      render :new
    end
  end
end

private
def chat_params
  params.require(:chat).permit(:chat1,:chat2,:chat3,:user_id)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    
    @haikus = Haiku.all.order("id DESC").page(params[:page]).per(4)
    
    # binding.pry
    
  end
  def sort
    @sort_haikus = Haiku.all.sort{|a,b| a.favorites.length <=> b.favorites.length}.reverse
    @haikus = Kaminari.paginate_array(@sort_haikus).page(params[:page]).per(4)
  end

  def pagenate
    params[:page] = params[:page].to_i + 1
    @haikus = Haiku.all.order("id DESC").page(params[:page]).per(4)
    # binding.pry
    puts "pagenateaaaaaaa#{params[:page]}"
    respond_to do |format|
      format.js
    end
    puts "ALLOKALLOKALLOKALLOKALLOKALLOK"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #ビフォーアクション　URL params[:id]で取得可能を取得してsessionと参照する
  before_action :check_login, only: [:show]
  def new

    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      # binding.pry
      flash[:info] = "成功しました"
      redirect_to user_url(@user)
      # redirect_to user_path_path(id: @user.id)
      # redirect_to "/users/#{@user.id}"
    else
      flash[:danger] = "失敗しました"
      binding.pry
      render :new
    end
  end
  def show
    @haikus = carrent_user.haikus.order("id DESC").page(params[:page]).per(4)
    @favorite_haikus = carrent_user.favorite_haikus.order("id DESC").page(params[:page]).per(4)
    @x = (carrent_user.haikus.length / 4.0).ceil
    @haikus2 = carrent_user.haikus.order("id DESC").limit(4).offset((@x-1) * 4)
    # binding.pry
  end
  def destroy
    User.destroy(session[:user_id])
    session[:user_id] = nil
    redirect_to new_user_path
  end
  def favorite_haiku
    # @favorite_haikus = carrent_user.favorite_haikus.limit(3)
    @favorite_haikus = carrent_user.favorite_haikus.order("id DESC").page(params[:page]).per(4)
    
    binding.pry
  end
  def sort
    @haikus = carrent_user.favorite_haikus.order("id DESC").page(params[:page]).per(4)
  end


  def pagenate
    params[:page] = params[:page].to_i + 1
    @haikus = Haiku.all.order("id DESC").page(params[:page]).per(4)
    # binding.pry
    puts "pagenateaaaaaaa#{params[:page]}"
    respond_to do |format|
      format.js
    end
    puts "ALLOKALLOKALLOKALLOKALLOKALLOK"
  end
end

private
def user_params
  params.require(:user).permit(:name,:email,:password,:password_digest)
end

def check_login
  if carrent_user == nil
    redirect_to sessions_new_path
  else
    if params[:id].to_i != carrent_user.id
        render template: 'errors/400'
        # redirect_to '/400'
        # render '/400'
    else
        nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def carrent_user
        @user = User.find_by(id: session[:user_id])
    end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/haikus_helper.rb
module HaikusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/javascripts/_pagination.js.erb

$("#haikus").append("<%= j(render partial: 'pages/haikus_index',locals: {haikus:@haikus})%>");
$('#haikus_paginate').remove();
$("#haikus_paginate").html("<div class='col-sm-6 offset-sm-3 mx-auto vw-375 sm-btn' style='display:block'><%= j(link_to_next_page @haikus,'次へ',class:'btn btn-secondary btn-block',remote:true)%></div>");
console.log("<%= j(params[:page]) %>");
$("#page").val("<%= j(params[:page]) %>");


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Haiku57Go1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <%= stylesheet_link_tag "https://use.fontawesome.com/releases/v5.6.1/css/all.css" %>
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Potta+One&display=swap"%>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
  </head>
  <body>
  <div class="flash">
    <% flash.each do |key, value|  %>
      <div class="alert alert-<%= key %> position-absolute top-0 w-100">
        <p><%= value %></p>
      </div>
    <% end %>
  </div>
  <nav class="navbar navbar-light navbar-expand-sm bg-success">
      <button class="navbar-toggler bg-white" type="button" data-toggle="collapse" data-target=".target" aria-expand="false" aria-controls=".target">
        <span class="navbar-toggler-icon"></span>
      </button>
      
    <%= link_to '俳句57Go',root_path,class:'navbar-brand text-white'%>

    <div class="btn btn-primary d-sm-none" data-toggle="collapse" data-target=".search2">検索</div>

    <div class="collapse navbar-collapse">
      <div class="navbar-nav mr-auto">
        <span class="nav-item">
          <%= link_to "一覧",pages_path,class:'nav-link text-white' %>
        </span>
        <% if carrent_user != nil %>
          <span class="nav-item">
            <%= link_to(user_url(carrent_user.id),class:'nav-link text-white') do %>
              <i class="far fa-user"></i>
              <span><%= carrent_user.name %></span>
            <% end %>
          </span>
          <span class="nav-item">
            <%= link_to "新規俳句",new_haiku_path,class:'nav-link text-white' %>
          </span>
          <span class="nav-item">
            <%= link_to "教室一覧",schools_path,class:'nav-link text-white' %>
          </span>
          <span class="nav-item">
            <%= link_to(logout_path,method: :delete,class:('nav-link logout_btn text-white')) do %>
              <i class="fas fa-sign-in-alt"></i>
              <span>ログアウト</span>
            <% end %>
          </span>
          <span class="nav-item">
            <%= link_to(chats_path,class:('nav-link text-white')) do %>
              <i class="fas"></i>
              <span>チャット</span>
            <% end %>
          </span>
        <% else %>
          <span class="nav-item">
           <%= link_to(new_user_path,class:'nav-link text-white') do %>
              <i class="far fa-user"></i>
              <span>新規登録</span>
            <% end %>
          </span>
          <span class="nav-item">
            <%= link_to(sessions_new_path,class:'nav-link text-white') do %>
              <i class="fas fa-sign-in-alt"></i>
              <span>ログイン</span>
            <% end %>
          </span>
        <%end%>
      </div>
      <% if controller_name == 'schools' %>
        <%= form_with url:schools_search_path,method: :get,local: :true,class:'form-inline' do |school|%>
          <div class="col-xs-4">
            <%= school.text_field :school,class:'form-control mr-2' %>
          </div>
          <%= school.submit "教室を検索" ,class:'btn btn-primary' %>
        <% end %>
      <% else %>
        <%= form_with url:haikus_search_path,method: :get,local: :true,class:'form-inline' do |haiku| %>
          <div class="col-xs-4">
            <%= haiku.text_field :haiku,class:'form-control mr-2' %>
          </div>
          <%= haiku.submit  "検索" ,class:'btn btn-primary' %>
        <% end %>
      <% end %>
    </div>
  </nav>

<%# 削除予定 %>
  <div class="col-sm-12 mx-0 my-0 px-0 py-0 position-relative">
    <%= form_with url:haikus_search_path,method: :get,local: :true,class:'form-inline collapse navbar-collapse' do |haiku| %>
      <div class="col-xs-4">
        <%= haiku.text_field :haiku,class:'form-control form-control-sm mr-2' %>
      </div>
      <%= haiku.submit :search ,class:'btn btn-primary btn-sm' %>
    <% end %>
  </div>

    <div class=" position-relative ">
        <div class="collapse navbar-collapse search2 position-absolute z-100 container bg-success">
         

          
            <% if controller_name == 'schools' %>
              

               <%= form_with url:schools_search_path,method: :get,local: :true,class:'form-inline my-3' do |school|%>
                
                    
                    <div class="col-6 offset-1 p-0">
                      <%= school.text_field :school,class:'form-control-sm mr-2 col-12 p-0' %>
                    </div>
                    <div class="col-5">
                      <%= school.submit "教室を検索" ,class:'btn btn-primary btn-sm  col-12' %>
                    </div>
              
                <% end %>

                
            <% else %>
                <%= form_with url:haikus_search_path,method: :get,local: :true,class:'form-inline my-3' do |haiku| %>
                <div class="col-7 offset-1 p-0">
                  <%= haiku.text_field :haiku,class:'form-control-sm mr-2  col-12 p-0' %>
                </div>
                <div class="col-4">
                  <%= haiku.submit "検索" ,class:'btn btn-primary btn-sm col-12' %>
                </div>
                <% end %>
            <% end %>
            </div>
          </div>

    </div>

  <div class="col-sm-12 mx-0 my-0 px-0 py-0 position-relative">
    <div class="collapse navbar-collapse target nav position-absolute w-100 z-100">
      <ul class="nav navbar-nav w-100 bg-success">
        <span class="nav-item border-bottom border-white px-3">
            <%= link_to "一覧",pages_path,class:'nav-link text-white' %>
        </span>
        <% if carrent_user != nil %>
          <span class="nav-item border-bottom border-white px-3">
            <%= link_to(user_url(carrent_user.id),class:'nav-link text-white') do %>
              <i class="far fa-user"></i>
              <span><%= carrent_user.name %></span>
            <% end %>
          </span>
          <span class="nav-item border-bottom border-white px-3">
            <%= link_to "新規俳句",new_haiku_path,class:'nav-link text-white' %>
          </span>
          <span class="nav-item border-bottom border-white px-3">
            <%= link_to "教室一覧",schools_path,class:'nav-link text-white' %>
          </span>
          <span class="nav-item border-bottom border-white px-3">
            <%= link_to(logout_path,method: :delete,class:('nav-link logout_btn text-white')) do %>
              <i class="fas fa-sign-in-alt"></i>
              <span>ログアウト</span>
            <% end %>
          </span>
          <span class="nav-item border-bottom border-white px-3">
            <%= link_to(chats_path,class:('nav-link text-white')) do %>
              <i class="fas"></i>
              <span>チャット</span>
            <% end %>
          </span>
        <% else %>
          <span class="nav-item border-bottom border-white px-3">
            <%= link_to(new_user_path,class:'nav-link text-white') do %>
              <i class="far fa-user"></i>
              <span>新規登録</span>
            <% end %>
          </span>
          <span class="nav-item border-bottom border-white px-3">
            <%= link_to(sessions_new_path,class:'nav-link text-white') do %>
              <i class="fas fa-sign-in-alt"></i>
              <span>ログイン</span>
              
            <% end %>
          </span>
        <%end%>
      </ul>
    </div>
  </div>

  <main class="container-md">
    <%= yield %>
  </main>
  </body>
  <%= params[:vali_error] %>

</html>

app/views/pages/_haikus_index.html.erb
<div class="row">
  <%= hidden_field_tag :control,controller_name,id:"control"%>
  <%= hidden_field_tag :page,params[:page].to_i,id:"page"%>

  <div class="col-sm-6 offset-sm-2" id="haikus">
    <% haikus.each do |haiku| %>
      <div class="haiku-<%= haiku.id %> row " >
        <div class=" col-sm-12  my-3">
          <div class="card border border-success rounded">
            <div class="card-body">
              <p class="haiku__text"><span><%= haiku.haiku1 %></span></p>
              <p class="haiku__text"><span><%= haiku.haiku2 %></span></p>
              <p class="haiku__text"><span><%= haiku.haiku3 %></span></p>
            </div>
            <div class="card-footer border-success">
            <%= haiku.id %>
              <% if carrent_user != nil %>
                <%= link_to(haiku_path(haiku.id ,haiku_id: haiku.id),class: :haiku__comment) do %>
                      <i class="fas fa-trash-alt"></i>
                      <%= haiku.comments.size %>
                      <span>コメント</span>
                <% end %>
                <% if User.find_by(id: haiku.user_id) == carrent_user %>
                  <%= link_to(haiku_path(haiku.id,haiku_id:haiku.id),method: :delete,remote: true,class: :haiku__del) do %>
                      <i class="fas fa-trash-alt"></i>
                      <span>削除</span>
                  <% end %>
                  <%= link_to(edit_haikus_path(haiku.id,haiku_id:haiku.id),class: :haiku__edit) do %>
                      <i class="fas fa-trash-alt"></i>
                      <span>編集</span>
                  <% end %>

                <% else %>
                  <%= render partial: "favorites/favorite",locals:{haiku:haiku,} %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-sm-4 banner my-3">
    <%= image_tag 'banner_pc.png',class:'pc'%>
    <%= image_tag 'banner_sp.png',class:'sp'%>
    
  </div>


</div>
    <div class="row" id="haikus_paginate">
      <div class="col-sm-6 offset-sm-2">
        <%= paginate @haikus %>
      </div>
      <div class="col-sm-6 offset-sm-2 vw-375 sm-btn">
        <%= link_to_next_page @haikus,'次へ',class:'btn btn-secondary btn-block',remote:true%>
      </div>
    </div>




app/views/pages/index.html.erb
<div class="row">
    <div class="col-sm-6 offset-sm-2">
        <h1>俳句一覧</h1>
        <%= link_to(sort_pages_path()) do%>
            <button class="btn btn-secondary">人気順へ</button>
        <% end %>
    </div>
</div>
<div id="haikus_block">
    <%= render partial: "pages/haikus_index",locals: {haikus:@haikus}%>
</div>

app/views/pages/index.js.erb

<%= render partial:'javascripts/pagination' %>

app/views/pages/pagenate.js.erb
<%= render partial:'javascripts/pagination' %>
console.log('bbbbb');

app/views/pages/sort.html.erb
<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <h1>最新ランキング</h1>
        <%= link_to(root_path()) do%>
            <button class="btn btn-secondary">最新の俳句へ</button>
        <% end %>
    </div>
</div>
<div id="haikus_block">
    <%= render partial: "pages/haikus_index",locals: {haikus:@haikus}%>
</div>





app/views/pages/sort.js.erb


 <%= render partial:'javascripts/pagination' %>